### Create a User
POST http://localhost:3000/auth/signup
content-type: application/json

{
    "email": "Mohamed@gmail.com",
    "password": "123",
    "message": "Hi, I am a hacker! Your dto MUST catch me"
} 