### Create a User
POST http://localhost:3000/auth/signup
content-type: application/json

{
    "email": "omar@gmail.com",
    "password": "12",
    "message": "Hi, I am a hacker! Your dto MUST catch me"
} 

### Find a particular user with a given ID
GET http://localhost:3000/auth/25


### Find all users with a given email
GET http://localhost:3000/auth?email=omar@gmail.com

### Delete a user with a given ID
DELETE  http://localhost:3000/auth/100

### Update a User with a given ID
PATCH http://localhost:3000/auth/100
content-type: application/json

{
    "password": "13"
} 
